CREATE TABLE accounts
(
    id      BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    user_id BIGINT                                  NOT NULL,
    amount  INTEGER                                 NOT NULL,
    name    VARCHAR(255)                            NOT NULL,
    created_at TIMESTAMP WITHOUT TIME ZONE DEFAULT NOW(),
    blocked_at TIMESTAMP WITHOUT TIME ZONE,
    closed_at  TIMESTAMP WITHOUT TIME ZONE,
    CONSTRAINT pk_accounts PRIMARY KEY (id)
);

ALTER TABLE accounts
    ADD CONSTRAINT uk_account_user_name UNIQUE (user_id, name);

ALTER TABLE accounts
    ADD CONSTRAINT USERS FOREIGN KEY (user_id) REFERENCES users (id);

