CREATE TABLE transactions
(
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    created_at  TIMESTAMP WITHOUT TIME ZONE DEFAULT NOW(),
    from_acc_id BIGINT                                  NOT NULL,
    to_acc_id   BIGINT                                  NOT NULL,
    amount      INTEGER,
    CONSTRAINT pk_transactions PRIMARY KEY (id)
);

CREATE INDEX idx_transactions_created_at ON transactions (created_at);

ALTER TABLE transactions
    ADD CONSTRAINT ACCOUNTS FOREIGN KEY (from_acc_id) REFERENCES accounts (id);

ALTER TABLE transactions
    ADD CONSTRAINT ACCOUNTSzHb0nV FOREIGN KEY (to_acc_id) REFERENCES accounts (id);